-- Love2D Hot Reload Bootstrap
-- Auto-generated by the love2d-hot-reload extension. Do not edit.

local PROJECT = "__PROJECT_PATH__"
local BRIDGE_PORT_FILE = "__BRIDGE_PORT_FILE__"
local HOT_POLL_INTERVAL = __HOT_POLL_INTERVAL_SECONDS__

-- Extend package.path so require() finds user modules via the real OS path too
package.path = PROJECT .. "/?.lua;" .. PROJECT .. "/?/init.lua;" .. package.path

-- User's main.lua is mirrored as __user_main.lua in this bootstrap dir.
-- love.filesystem finds it directly — no mounting needed.
local chunk, err = love.filesystem.load("__user_main.lua")
assert(chunk, "[love2d] Could not load main.lua: " .. tostring(err))
chunk()

-- Inject hot reload on top of whatever love callbacks the user defined
_G.__LOVE2D_HOT_POLL_INTERVAL = HOT_POLL_INTERVAL
_G.__LOVE2D_PROJECT_PATH = PROJECT
_G.__LOVE2D_BRIDGE_PORT_FILE = BRIDGE_PORT_FILE
require("__hot__")
