-- Love2D Hot Reload Bootstrap (conf.lua proxy)
-- Auto-generated by the love2d-hot-reload extension. Do not edit.
-- love.filesystem is NOT available yet here, so we use Lua's native loadfile().
local fn = loadfile("__PROJECT_PATH__/conf.lua")
if fn then fn() end
