-- hot.lua — Love2D bridge + hot reload
-- Auto-generated by the love2d-hot-reload extension. Do not edit.

local socket_ok, socket = pcall(require, "socket")
if not socket_ok then
    print("[hot] socket module unavailable; bridge disabled: " .. tostring(socket))
    return
end

local project_path = rawget(_G, "__LOVE2D_PROJECT_PATH") or "."
local port_file = rawget(_G, "__LOVE2D_BRIDGE_PORT_FILE") or (project_path .. "/.love2d-hot-port")
local startup_error_file = rawget(_G, "__LOVE2D_STARTUP_ERROR_FILE")
local server = nil
local client = nil
local original_print = print
local unpack_values = table.unpack or unpack
local bridge_degraded = false
local bridge_shutdown = false
local send_line
local encode_json
local emit_log_line
local wrapped_callbacks = {}

function emit_log_line(message, flush)
    if not client then
        return
    end

    local payload = encode_json({
        type = "log",
        data = message
    }) .. "\n"

    if flush then
        local previous_timeout = client:gettimeout()
        client:settimeout(0.1)
        client:send(payload)
        client:settimeout(previous_timeout)
        return
    end

    send_line(payload)
end

local function log(message)
    local line = "[hot] " .. message
    original_print(line)
    emit_log_line(line, false)
end

local function traceback_message(message)
    return debug.traceback(tostring(message), 2)
end

local function delete_port_file()
    os.remove(port_file)
end

local function write_startup_error(message)
    if not startup_error_file then
        return
    end

    local file = io.open(startup_error_file, "w")
    if not file then
        return
    end

    file:write(message)
    file:close()
end

local function shutdown_bridge_runtime(reason)
    if bridge_shutdown then
        return
    end

    bridge_shutdown = true
    local shutdown_line = "[hot] bridge runtime stopped: " .. tostring(reason)
    original_print(shutdown_line)
    emit_log_line(shutdown_line, true)

    if client then
        client:close()
        client = nil
    end
    if server then
        server:close()
        server = nil
    end

    delete_port_file()
    print = original_print
end

local function mark_bridge_degraded(reason)
    if bridge_degraded then
        return
    end

    bridge_degraded = true
    write_startup_error(reason)
    log(reason)
    shutdown_bridge_runtime(reason)
end

local function safe_call(label, fn, ...)
    local packed_args = { ... }
    return xpcall(function()
        return fn(unpack_values(packed_args))
    end, function(message)
        local trace = traceback_message(message)
        mark_bridge_degraded(label .. ": " .. trace)
        return trace
    end)
end

function send_line(payload)
    if not client then
        return
    end

    local ok, err = client:send(payload)
    if not ok then
        original_print("[hot] send error: " .. tostring(err))
        client:close()
        client = nil
    end
end

function encode_json(value)
    local t = type(value)
    if t == "string" then
        local escaped = value:gsub("\\", "\\\\"):gsub('"', '\\"'):gsub("\n", "\\n"):gsub("\r", "\\r"):gsub("\t", "\\t")
        escaped = escaped:gsub("[%z\1-\31]", function(ch)
            return string.format("\\u%04x", ch:byte())
        end)
        return '"' .. escaped .. '"'
    elseif t == "number" or t == "boolean" then
        return tostring(value)
    elseif t == "nil" then
        return "null"
    elseif t == "table" then
        local is_array = #value > 0
        local parts = {}
        if is_array then
            for i = 1, #value do
                parts[#parts + 1] = encode_json(value[i])
            end
            return "[" .. table.concat(parts, ",") .. "]"
        end

        for k, v in pairs(value) do
            if type(k) == "string" then
                parts[#parts + 1] = encode_json(k) .. ":" .. encode_json(v)
            end
        end
        return "{" .. table.concat(parts, ",") .. "}"
    end

    return "null"
end

local function decode_json(str)
    local chunk, err = load("return " .. str
        :gsub("null", "nil")
        :gsub("%[", "{")
        :gsub("%]", "}")
        :gsub('"([^"]-)":', '["%1"]='))
    if not chunk then
        return nil, err
    end

    local ok, result = safe_call("json decode failed", chunk)
    if not ok then
        return nil, result
    end

    return result
end

local function write_port_file(port)
    local file = io.open(port_file, "w")
    if not file then
        log("failed to write port file at " .. port_file)
        return
    end

    file:write(tostring(port))
    file:close()
end

local function merge_module(old_module, new_module)
    for key in pairs(old_module) do
        if new_module[key] == nil then
            old_module[key] = nil
        end
    end

    for key, value in pairs(new_module) do
        old_module[key] = value
    end

    if rawget(old_module, "__index") == new_module then
        old_module.__index = old_module
    end

    local mt = getmetatable(new_module)
    if mt then
        setmetatable(old_module, mt)
    end

    return old_module
end

local function reload_module(module_name)
    if bridge_degraded then
        return false, "bridge is in degraded state after a previous runtime error; restart required"
    end

    if not module_name or package.loaded[module_name] == nil then
        return false, "module not loaded: " .. tostring(module_name)
    end

    local old_module = package.loaded[module_name]
    package.loaded[module_name] = nil

    local ok, new_module = safe_call("module reload failed for " .. tostring(module_name), require, module_name)
    if not ok then
        package.loaded[module_name] = old_module
        return false, tostring(new_module)
    end

    if type(old_module) == "table" and type(new_module) == "table" then
        package.loaded[module_name] = merge_module(old_module, new_module)
        return true, "merged table module"
    end

    return true, "re-required non-table module"
end

local function handle_command(line)
    local message, decode_err = decode_json(line)
    if not message or not message.cmd then
        log("failed to decode command: " .. tostring(decode_err))
        return
    end

    local response = {
        id = message.id,
        type = "response",
        success = false
    }

    if message.cmd == "reload" then
        local ok, result = reload_module(message.module)
        response.success = ok
        if ok then
            response.data = result
            log("bridge reloaded module " .. tostring(message.module) .. ": " .. tostring(result))
        else
            response.error = result
            log("bridge reload failed for " .. tostring(message.module) .. ": " .. tostring(result))
        end
    elseif message.cmd == "ping" then
        response.success = true
        response.data = "pong"
    else
        response.error = "unknown command: " .. tostring(message.cmd)
    end

    send_line(encode_json(response) .. "\n")
end

local function hook_print()
    print = function(...)
        original_print(...)
        if not client then
            return
        end

        local parts = {}
        for i = 1, select("#", ...) do
            parts[i] = tostring(select(i, ...))
        end

        send_line(encode_json({
            type = "log",
            data = table.concat(parts, "\t")
        }) .. "\n")
    end
end

local function wrap_callback(name)
    local original_callback = love[name]
    if type(original_callback) ~= "function" then
        return
    end

    if wrapped_callbacks[name] == original_callback then
        return
    end

    local wrapped = function(...)
        local packed_args = { ... }
        local ok, result = xpcall(function()
            return original_callback(unpack_values(packed_args))
        end, function(message)
            local trace = traceback_message(message)
            mark_bridge_degraded("callback " .. name .. " failed: " .. trace)
            return trace
        end)

        if not ok then
            error(result, 0)
        end

        return result
    end

    wrapped_callbacks[name] = wrapped
    love[name] = wrapped
end

local function wrap_callbacks()
    for _, callback_name in ipairs({
        "load",
        "update",
        "draw",
        "displayrotated",
        "filedropped",
        "directorydropped",
        "dropcomplete",
        "keypressed",
        "keyreleased",
        "joystickadded",
        "joystickaxis",
        "joystickhat",
        "joystickpressed",
        "joystickreleased",
        "joystickremoved",
        "gamepadaxis",
        "gamepadpressed",
        "gamepadreleased",
        "mousepressed",
        "mousereleased",
        "mousemoved",
        "wheelmoved",
        "touchpressed",
        "touchreleased",
        "touchmoved",
        "textinput",
        "textedited",
        "resize",
        "visible",
        "focus",
        "lowmemory",
        "quit",
        "threaderror"
    }) do
        wrap_callback(callback_name)
    end
    log("callback guards installed")
end

local function start_server()
    server = socket.tcp()
    server:settimeout(0)

    local requested_port = tonumber(os.getenv("LOVE2D_HOT_PORT")) or 0
    local ok, err = server:bind("127.0.0.1", requested_port)
    if not ok then
        log("failed to bind bridge socket: " .. tostring(err))
        server:close()
        server = nil
        return
    end

    server:listen(1)
    local _, assigned_port = server:getsockname()
    write_port_file(assigned_port)
    log("bridge listening on port " .. tostring(assigned_port))
end

local function bridge_update()
    if bridge_shutdown or not server then
        return
    end

    if not client then
        local accepted = server:accept()
        if accepted then
            accepted:settimeout(0)
            client = accepted
            log("bridge client connected")
        end
    end

    while client do
        local line, err = client:receive("*l")
        if line then
            handle_command(line)
        else
            if err == "closed" then
                log("bridge client disconnected")
                client:close()
                client = nil
            end
            break
        end
    end
end

local function bridge_quit()
    shutdown_bridge_runtime("normal shutdown")
end

start_server()
hook_print()
_G.__LOVE2D_WRAP_CALLBACKS = wrap_callbacks

local original_run = love.run
if original_run then
    love.run = function()
        local step = original_run()
        return function()
            bridge_update()
            local result = step()
            if result then
                bridge_quit()
            end
            return result
        end
    end
end

log("bridge active via love.run hook")
